### PR TITLE
Use dub as fallback if BUILD_TOOL isn't defined

### PR DESCRIPTION
**Pull request by wilzbach**

### CODE REVIEW

**Comment by schveiguy** [comment]
I'm going to try the other option. I don't really want to change this repository for an external reason. I'll leave this open in case the other option doesn't work.

**Comment by wilzbach** [comment]
It's not only for external tools. This allows one to run the Travis script locally without any variable setup as well. IMHO it's a good practice for scripts to allows provide a sane default config/fallback.

**Comment by schveiguy** [comment]
Is running the travis.sh a thing other than in travis (and our CI setup)? I just didn't think it would be something worth messing with.

It does make sense to alter the shell script so it doesn't crash when certain variables aren't set, just on principle. I have to have a default for COVERAGE too.

**Comment by schveiguy** [comment]
I will look at doing the COVERAGE variable too. And maybe testing.

**Pull request closed without merging**
