### PR TITLE
Fixes #32 - Cast the null to shared(Driver) to appease the cas template.

### LINKED ISSUE #32: dmd 2.089.0 reports error
There is an error with cas in dmd 2.089.0. The cas call should work as is in std.io, but fails. There are workarounds, but I'm expecting the bug to be fixed (https://issues.dlang.org/show_bug.cgi?id=20359). Once it's fixed, I'll fix io.

### PR DESCRIPTION
**Pull request by schveiguy**
ping @jondegenhardt I think this will have it build again. Can you test possibly before I merge?

### CODE REVIEW

**Comment by jondegenhardt** [comment]
I'm pretty busy today, I might be able to get to it tonight though.

**Comment by schveiguy** [comment]
OK, looks like all the things that were failing on CI are now green. So I'm just going to pull the lever and maybe your CI will go green as well.

**Comment by jondegenhardt** [comment]
Last time you updated the version number in the meson build file, but I don't see a change to that file. Did you miss this?

**Comment by schveiguy** [comment]
Ugh, yes. That was a problem I was concerned with (forgetting to update this build number), but it apparently is expected practice. Will update and move the tag.

**Comment by jondegenhardt** [comment]
For my own repos I have a "steps to do a release" notes file. Otherwise I'd forget. Little stuff like signing the commit tag.

**Comment by schveiguy** [comment]
@jondegenhardt updated meson build, and moved the tag.

**Comment by jondegenhardt** [comment]
Build succeeded on all compiler versions except for DMD v2.089.0. See [https://travis-ci.com/jondegenhardt/dcat-perf/builds/149768223](https://travis-ci.com/jondegenhardt/dcat-perf/builds/149768223). The CI has 17 different DMD/LDC/Linux/OSX combos, so its got fair coverage.

**Comment by jondegenhardt** [comment]
However, that my CI doesn't explicitly test DMD 2.090.0. It does test latest, which is DMD 2.090.1. That release passed.

**Comment by schveiguy** [comment]
That was a regression, 2.089.1 works.

https://github.com/dlang/druntime/pull/2853

**Comment by jondegenhardt** [comment]
Excellent, thanks. I'll remove 2.089.0 from my CI tests.

**Pull request merged**
